### ISSUE TITLE
Update Towncrier config in pyproject.toml

### ISSUE THREAD

**Issue by Nagidal** [python-semver/python-semver#374]
# Situation
Current towncrier configuration uses a deprecated format (see Towncrier's [configuration reference](https://towncrier.readthedocs.io/en/stable/configuration.html#custom-fragment-types))

```toml
  [[tool.towncrier.type]]
  directory = "trivial"
  name = "Trivial/Internal Changes"
  showcontent = true
```

# Expected Behavior
Use the new format:
```toml
  [tool.towncrier.fragment.trivial]
  name = "Trivial/Internal Changes"
  showcontent = true
```
(array of toml tables is [deprecated](https://towncrier.readthedocs.io/en/stable/configuration.html#deprecated-defining-custom-fragment-types-with-an-array-of-toml-tables))
