### ISSUE TITLE
Consistent Title Case in Changelog Headings

### ISSUE THREAD

**Issue by Nagidal** [python-semver/python-semver#378]
Sorry, this issue has arisen through my own [sloppy review](https://github.com/python-semver/python-semver/pull/375#pullrequestreview-1194877897). Let's be consistent with the Title Case.

In the Towncrier configuration we have "Breaking Changes", "Trivial/Internal Changes", so we should have "Improved Documentation", "Bug Fixes".

# Situation
```toml
[tool.towncrier.fragment.bugfix]
name = "Bug fixes"

[tool.towncrier.fragment.doc]
name = "Improved documentation"
```

# Expected Behavior
```toml
[tool.towncrier.fragment.bugfix]
name = "Bug Fixes"

[tool.towncrier.fragment.doc]
name = "Improved Documentation"
```
